version: "2"

services:

  identiorca:
    hostname: identiorca.weave.local
    image: amouat/identiorca
    environment:
     USE_IP_ADDR: "1"
    ports:
     - "9090"

  dnmonster:
    hostname: dnmonster.weave.local
    image: amouat/dnmonster:1.0

  redis:
    hostname: redis.weave.local
    image: redis:3

  
